### ISSUE TITLE
[Error] How do you add your custom dataset to train?

### ISSUE THREAD

**Issue by YukiSakuma** [mit-han-lab/data-efficient-gans#11]
Sorry I am kind of new to this but based on my experience using StyleGAN2 you convert your images to tfrecords files so I assume you also do this in when using DiffAugment-StyleGAN2 so when I run this in Colab

`!python run_cifar.py --metrics=none --mirror-augment=True --total-kimg=5000 --result-dir='/content/drive/My Drive/storage/mydataset' --num-gpus=1 --resume="/content/drive/My Drive/pretrainednetworksnapshot-0XXXX.pkl" --DiffAugment=color,cutout,translation --resolution=512 --dataset='/content/drive/My Drive/mydataset'`

where `mydataset` is the folder which contains the tfrecords file but I am getting an error 

```
dnnlib: Running training.training_loop.training_loop() on localhost...
Streaming data using training.dataset.TFRecordDataset...
Traceback (most recent call last):
  File "run_cifar.py", line 171, in <module>
    main()
  File "run_cifar.py", line 165, in main
    run(**vars(args))
  File "run_cifar.py", line 95, in run
    dnnlib.submit_run(**kwargs)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/training/training_loop.py", line 158, in training_loop
    training_set = dataset.load_dataset(verbose=True, **dataset_args)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/training/dataset.py", line 245, in load_dataset
    dataset = dnnlib.util.get_obj_by_name(class_name)(**kwargs)
  File "/content/data-efficient-gans-master/DiffAugment-stylegan2/training/dataset.py", line 113, in __init__
    dset, info = tfds.load(name=self.name, data_dir=tfds_data_dir, split=split, with_info=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 292, in load
    name, name_builder_kwargs = _dataset_name_and_kwargs_from_name_str(name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 339, in _dataset_name_and_kwargs_from_name_str
    raise ValueError(_NAME_STR_ERR.format(name_str))
ValueError: Parsing builder name string /content/drive/My Drive/mydataset failed.
The builder name string must be of the following format:
  dataset_name[/config_name][:version][/kwargs]

  Where:

    * dataset_name and config_name are string following python variable naming.
    * version is of the form x.y.z where {x,y,z} can be any digit or *.
    * kwargs is a comma list separated of arguments and values to pass to
      builder.

  Examples:
    my_dataset
    my_dataset:1.2.*
    my_dataset/config1
    my_dataset/config1:1.*.*
    my_dataset/config1/arg1=val1,arg2=val2
    my_dataset/config1:1.2.3/right=True,foo=bar,rate=1.2
```
Then I read the readme for DiffAugment-StyleGAN2 which says

`... After putting all images into a single folder, pass it to WHICH_DATASET, the images will be resized to the specified resolution if necessary, and then enjoy the outputs! `

So I thought you would just put your images to that folder and pass it to WHICH_DATASET and it would automatically convert that to a tfrecord file? So I just did that but I am still getting the same error as above. Please help.

**Comment by YukiSakuma** [comment]
Well I found my problem,  it was a really simple one you have to use 
`!python run_few_shots.py` instead of `!python run_cifar.py`
where `run_few_shots.py` is equivalent to `run_training.py` in the original StyleGAN2

but I am getting an OOM error now, what should be the proper batch size and GPU for a 512px resolution?
In the original StyleGAN2 code I use 128 batch and 8 GPU using a P100 in Colab

**Comment by zsyzzsoft** [comment]
I haven't tried 512 resolution on a single GPU, but I guess reducing the batch size to 16 or 8 would work.
