### ISSUE TITLE
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.

### ISSUE THREAD

**Issue by ak9250** [mit-han-lab/data-efficient-gans#28]
Traceback (most recent call last):
  File "run_low_shot.py", line 16, in <module>
    from metrics import metric_base
  File "/content/data-efficient-gans/DiffAugment-stylegan2/metrics/metric_base.py", line 18, in <module>
    from training import dataset
  File "/content/data-efficient-gans/DiffAugment-stylegan2/training/dataset.py", line 14, in <module>
    import tensorflow_datasets as tfds
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/__init__.py", line 51, in <module>
    from tensorflow_datasets import __init__py3 as api
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/__init__py3.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tf_compat.py", line 59, in ensure_tf_install
    "This version of TensorFlow Datasets requires TensorFlow "
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.

**Comment by shengyu-ponyai** [comment]
Please try `pip install tensorflow-datasets==2.1.0`

**Comment by zsyzzsoft** [comment]
Please try `pip install tensorflow-datasets==2.1.0`

**Comment by ak9250** [comment]
ok thanks!
