### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2'has no attribute 'contrib'

### ISSUE THREAD

**Issue by hzc5095** [mit-han-lab/data-efficient-gans#46]
When trying to train the model with a custom dataset,There was an error. Checking the information found that the TensorFlow version needs to be upgraded, but you need version 1.14. Is this a contradiction?My installed version is 1.14。

**Comment by shengyu-ponyai** [comment]
Please install tensorflow 1.14 or 1.15 and `pip install tensorflow-datasets==2.1.0`.

**Comment by zsyzzsoft** [comment]
Please install tensorflow 1.14 or 1.15 and `pip install tensorflow-datasets==2.1.0`.

**Comment by hzc5095** [comment]
conda list:
tensorboard                 1.14.0
tensorflow-datasets     2.1.0
tensorflow-estimator   1.14.0
tensorflow-gpu            1.14.0
tensorflow-metadata   0.26.0

Is that right? There still has this problem. Thank you

**Comment by zsyzzsoft** [comment]
Could you post the error message?

**Comment by hzc5095** [comment]
Traceback (most recent call last):
  File "run_low_shot.py", line 16, in <module>
    from metrics import metric_base
  File "/home/haozengchao/data-efficient-gans-master/data-efficient-gans-master/DiffAugment-stylegan2/metrics/metric_base.py", line 18, in <module>
    from training import dataset
  File "/home/haozengchao/data-efficient-gans-master/data-efficient-gans-master/DiffAugment-stylegan2/training/dataset.py", line 14, in <module>
    import tensorflow_datasets as tfds
  File "/home/haozengchao/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_datasets/__init__.py", line 46, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/home/haozengchao/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_datasets/core/__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "/home/haozengchao/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_datasets/core/tf_compat.py", line 66, in ensure_tf_install
    _patch_tf(tf)
  File "/home/haozengchao/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_datasets/core/tf_compat.py", line 80, in _patch_tf
    _patch_for_tf1_13(tf)
  File "/home/haozengchao/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_datasets/core/tf_compat.py", line 96, in _patch_for_tf1_13
    tf.contrib.autograph.do_not_convert)
AttributeError: module 'tensorflow.compat.v2' has no attribute 'contrib'

**Comment by zsyzzsoft** [comment]
Seems that tensorflow 1.14 is not compatible with tensorflow-datasets 2.1.0. Please install tensorflow 1.15 instead of 1.14. Sorry for the confusion.

**Comment by hzc5095** [comment]
Thank you .
