### ISSUE TITLE
Problem in training with partial data in DiffAugment-stylegan2

### ISSUE THREAD

**Issue by YYingH** [mit-han-lab/data-efficient-gans#9]
Thanks for your contribution! 
I got errors when I run the following command.
```python
python run_cifar.py --dataset=cifar10 --num-samples=5000 --num-gpus=2 --DiffAugment=color,translation,cutout
```
I also found this error only appears when setting **num-samples**. 

The details are as follows:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[{{node GPU0/DataFetch/IteratorGetNext}}]]
  (1) Out of range: End of sequence
         [[{{node GPU0/DataFetch/IteratorGetNext}}]]
         [[GPU0/DataFetch/IteratorGetNext/_3169]]
0 successful operations.
1 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_cifar.py", line 167, in <module>
    main()
  File "run_cifar.py", line 161, in main
    run(**vars(args))
  File "run_cifar.py", line 91, in run
    dnnlib.submit_run(**kwargs)
  File "/tf/code/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/tf/code/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/tf/code/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/tf/code/training/training_loop.py", line 291, in training_loop
    tflib.run(D_train_op, feed_dict)
  File "/tf/code/dnnlib/tflib/tfutil.py", line 31, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[node GPU0/DataFetch/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Out of range: End of sequence
         [[node GPU0/DataFetch/IteratorGetNext (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[GPU0/DataFetch/IteratorGetNext/_3169]]
0 successful operations.
1 derived errors ignored.

Original stack trace for 'GPU0/DataFetch/IteratorGetNext':
  File "run_cifar.py", line 167, in <module>
    main()
  File "run_cifar.py", line 161, in main
    run(**vars(args))
  File "run_cifar.py", line 91, in run
    dnnlib.submit_run(**kwargs)
  File "/tf/code/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/tf/code/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/tf/code/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/tf/code/training/training_loop.py", line 202, in training_loop
    reals_read, labels_read = training_set.get_minibatch_tf()
  File "/tf/code/training/dataset.py", line 171, in get_minibatch_tf
    return self._tf_iterator.get_next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```
Envs: 
Python 3.6
CUDA  10.0
tensorflow-gpu: 1.15.2

**Comment by zsyzzsoft** [comment]
It seems to be an issue related to the newest version of tensorflow-datasets. Try `pip install tensorflow-datasets==2.1.0` for a temporary workaround.

**Comment by YYingH** [comment]
Thanks for the reply, it works!
